id: P000636
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:54:29.787329
source_metadata:
  id: bdr:W20171
  title: སྟོད་ལུང་བདེ་ཆེན་རྫོང་།
  author: ''
  volumes:
    3189949a11064d508ec5adb18d947803:
      image_group_id: I1GS55147
      title: ''
      volume_number: 1
      total_pages: 75
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
